# Generated by Django 2.1.2 on 2018-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=2)),
                ('countryCode', models.CharField(max_length=3)),
                ('userId', models.IntegerField(default=0)),
                ('clickType', models.CharField(max_length=16)),
                ('clickDate', models.DateField(verbose_name='clickDate')),
                ('itemId', models.IntegerField()),
                ('page', models.IntegerField(default=1)),
                ('rows', models.IntegerField()),
            ],
        ),
    ]
