# Generated by Django 2.1.2 on 2018-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=2)),
                ('countryCode', models.CharField(max_length=3)),
                ('userId', models.IntegerField(default=0, null=True)),
                ('clickType', models.CharField(max_length=16)),
                ('clickDate', models.DateTimeField(db_column='clickDate')),
                ('itemId', models.IntegerField()),
                ('page', models.IntegerField(default=1, null=True)),
                ('rows', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'clicks_recommend',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField(db_column='itemId')),
                ('percentItem', models.FloatField(db_column='percentItem')),
            ],
            options={
                'db_table': 'items_recommend',
            },
        ),
        migrations.CreateModel(
            name='ItemsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField(db_column='itemId')),
                ('state', models.CharField(db_column='state', max_length=3)),
            ],
            options={
                'db_table': 'items_recommend_state',
            },
        ),
        migrations.CreateModel(
            name='OneItemsCategories',
            fields=[
                ('itemId', models.BigIntegerField(db_column='itemId', primary_key=True, serialize=False)),
                ('categoryId', models.BigIntegerField(db_column='categoryId')),
            ],
            options={
                'db_table': 'one_items_categories',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0, null=True)),
                ('market', models.CharField(max_length=2)),
                ('countryCode', models.CharField(max_length=3)),
                ('categoryId', models.BigIntegerField(db_column='categoryId')),
                ('categoryPercentage', models.FloatField()),
                ('isNext', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(to='check.Items')),
            ],
            options={
                'db_table': 'results_recommend',
            },
        ),
        migrations.AlterUniqueTogether(
            name='oneitemscategories',
            unique_together={('itemId', 'categoryId')},
        ),
    ]
