# Generated by Django 2.1.2 on 2018-10-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='"check_data_test"',
        ),
    ]
